# MongoDB 集群部署配置（生产环境）
version: '3.8'

services:
  # MongoDB 主节点
  mongo1:
    image: registry.cn-hangzhou.aliyuncs.com/library/mongo:7
    container_name: tradingagents-mongo1
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=tradingagents123
      - MONGO_INITDB_DATABASE=tradingagents
    volumes:
      - mongo1_data:/data/db
      - mongo1_config:/data/configdb
    command: mongod --replSet rs0 --auth --keyFile /data/replica.key
    networks:
      - tradingagents-network
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

  # MongoDB 副本节点1
  mongo2:
    image: registry.cn-hangzhou.aliyuncs.com/library/mongo:7
    container_name: tradingagents-mongo2
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=tradingagents123
    volumes:
      - mongo2_data:/data/db
      - mongo2_config:/data/configdb
    command: mongod --replSet rs0 --auth --keyFile /data/replica.key
    networks:
      - tradingagents-network
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

  # MongoDB 副本节点2
  mongo3:
    image: registry.cn-hangzhou.aliyuncs.com/library/mongo:7
    container_name: tradingagents-mongo3
    ports:
      - "27019:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=tradingagents123
    volumes:
      - mongo3_data:/data/db
      - mongo3_config:/data/configdb
    command: mongod --replSet rs0 --auth --keyFile /data/replica.key
    networks:
      - tradingagents-network
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

  # MongoDB 初始化容器
  mongo-setup:
    image: registry.cn-hangzhou.aliyuncs.com/library/mongo:7
    container_name: tradingagents-mongo-setup
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    volumes:
      - ./scripts/setup-replica-set.js:/setup-replica-set.js:ro
    command: >
      bash -c "
        sleep 10 &&
        mongosh --host mongo1:27017 -u admin -p tradingagents123 --authenticationDatabase admin /setup-replica-set.js
      "
    networks:
      - tradingagents-network

  # Redis 集群（可选）
  redis-master:
    image: registry.cn-hangzhou.aliyuncs.com/library/redis:7-alpine
    container_name: tradingagents-redis-master
    ports:
      - "6379:6379"
    volumes:
      - redis_master_data:/data
    command: redis-server --appendonly yes --maxmemory 2gb --maxmemory-policy allkeys-lru
    networks:
      - tradingagents-network

  redis-slave:
    image: registry.cn-hangzhou.aliyuncs.com/library/redis:7-alpine
    container_name: tradingagents-redis-slave
    ports:
      - "6380:6379"
    volumes:
      - redis_slave_data:/data
    command: redis-server --appendonly yes --slaveof redis-master 6379
    depends_on:
      - redis-master
    networks:
      - tradingagents-network

  # MongoDB 监控（可选）
  mongo-express:
    image: registry.cn-hangzhou.aliyuncs.com/library/mongo-express:latest
    container_name: tradingagents-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=tradingagents123
      - ME_CONFIG_MONGODB_SERVER=mongo1
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=tradingagents123
    depends_on:
      - mongo1
    networks:
      - tradingagents-network

networks:
  tradingagents-network:
    driver: bridge

volumes:
  mongo1_data:
  mongo1_config:
  mongo2_data:
  mongo2_config:
  mongo3_data:
  mongo3_config:
  redis_master_data:
  redis_slave_data:
