# 测试服务配置
version: '3.8'

services:
  # 简单测试服务
  test-service:
    image: docker.m.daocloud.io/library/python:3.10-slim
    container_name: tradingagents-test-service
    ports:
      - "8002:8002"
    environment:
      - PYTHONPATH=/app:/app/backend
      - MONGODB_URL=mongodb://admin:tradingagents123@mongodb:27017/tradingagents?authSource=admin
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./test-service.py:/app/test-service.py:ro
      - ../backend:/app/backend:ro
      - ../:/app/project:ro
    working_dir: /app
    command: >
      sh -c "
        pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple/ &&
        pip config set global.trusted-host pypi.tuna.tsinghua.edu.cn &&
        pip install fastapi uvicorn &&
        python test-service.py
      "
    networks:
      - tradingagents-network
    depends_on:
      - mongodb
      - redis

  # Redis 缓存服务
  redis:
    image: docker.m.daocloud.io/library/redis:7-alpine
    container_name: tradingagents-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - tradingagents-network
    restart: unless-stopped

  # MongoDB 主数据库
  mongodb:
    image: docker.m.daocloud.io/library/mongo:7
    container_name: tradingagents-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=tradingagents123
      - MONGO_INITDB_DATABASE=tradingagents
    volumes:
      - mongodb_data:/data/db
    networks:
      - tradingagents-network
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  tradingagents-network:
    driver: bridge
